In [1]:
import json
import requests
import pandas as pd
import time

In [2]:
response = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/objects')
response.json()

{'total': 488621,
 'objectIDs': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  56,
  57,
  58,
  59,
  62,
  63,
  64,
  65,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  145,
  146,
  147,
  148,
  150,
  151,
  154,
  165,
  166,
  170,
  171,
  172,
  173,
  174,
  176,
  177,
  179,
  180,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  198,
  199,
  200,
  201,
  202,
  203,
  204,
  205,
  206,
  208,
  209,
  211,
  212,
  213,
  214,
  215,
  216,
  218,
  219,
  220,
  221,
  222,
  223,
  224,
  225,
  226,
  227,
  228,
  229,
  230,
  231,
  232,
  233,
  234,
  235,
  236,
  237,
  238,
  239,
  240,
  243,
  244,
  245,
  246,
  247,
  248,
  249,
  252,
  253,
  254,
  255,
  257,
  258,
  259,
  260,
  261,
  262,
  263,
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  287,
  288,
  289,
  290,
  291,
  292,
  293,
  294,
  295,
  296,
  297,
  298,
  299,
  300,
  301,
  303,
  304,
  305,
  306,
  307,
  308,
  309,
  310,
  311,
  312,
  313,
  314,
  315,
  316,
  317,
  318,
  319,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  331,
  332,
  333,
  334,
  335,
  336,
  337,
  338,
  339,
  340,
  341,
  342,
  343,
  344,
  345,
  346,
  347,
  348,
  349,
  350,
  351,
  352,
  353,
  354,
  355,
  356,
  358,
  359,
  360,
  361,
  362,
  363,
  364,
  365,
  366,
  367,
  368,
  369,
  370,
  371,
  372,
  373,
  374,
  376,
  377,
  378,
  379,
  380,
  381,
  382,
  383,
  384,
  385,
  386,
  387,
  388,
  389,
  394,
  395,
  396,
  397,
  398,
  399,
  400,
  401,
  402,
  403,
  404,
  405,
  406,
  407,
  408,
  409,
  410,
  411,
  415,
  416,
  417,
  418,
  419,
  420,
  421,
  422,
  423,
  424,
  425,
  426,
  427,
  428,
  429,
  430,
  431,
  432,
  433,
  434,
  435,
  436,
  437,
  438,
  439,
  442,
  443,
  444,
  445,
  446,
  447,
  448,
  449,
  450,
  451,
  452,
  453,
  454,
  455,
  457,
  458,
  459,
  461,
  462,
  463,
  464,
  465,
  466,
  467,
  468,
  469,
  470,
  471,
  472,
  473,
  474,
  475,
  476,
  477,
  478,
  479,
  480,
  481,
  482,
  483,
  484,
  485,
  486,
  487,
  488,
  489,
  490,
  491,
  492,
  493,
  494,
  495,
  496,
  497,
  498,
  499,
  500,
  501,
  502,
  504,
  505,
  506,
  507,
  508,
  509,
  510,
  511,
  512,
  2339,
  2340,
  2341,
  2342,
  2343,
  2344,
  2345,
  2346,
  2347,
  2348,
  2349,
  2351,
  2352,
  2353,
  2354,
  2355,
  2356,
  2357,
  2358,
  2359,
  2360,
  2361,
  2362,
  2363,
  2364,
  2365,
  2366,
  2367,
  2368,
  2369,
  2370,
  2371,
  2372,
  2373,
  2374,
  2375,
  2376,
  2377,
  2378,
  2379,
  2380,
  2381,
  2382,
  2383,
  2384,
  2385,
  2386,
  2387,
  2388,
  2389,
  2390,
  2391,
  2392,
  2393,
  2394,
  2395,
  2396,
  2397,
  513,
  514,
  515,
  516,
  517,
  519,
  520,
  521,
  522,
  523,
  524,
  525,
  526,
  527,
  528,
  529,
  530,
  531,
  532,
  533,
  534,
  535,
  536,
  537,
  538,
  539,
  540,
  541,
  542,
  543,
  544,
  545,
  546,
  547,
  548,
  549,
  550,
  551,
  552,
  553,
  554,
  555,
  556,
  559,
  560,
  561,
  562,
  564,
  565,
  566,
  567,
  568,
  569,
  570,
  571,
  572,
  573,
  574,
  575,
  576,
  577,
  578,
  579,
  580,
  581,
  582,
  583,
  584,
  585,
  586,
  587,
  588,
  589,
  590,
  591,
  592,
  593,
  594,
  595,
  596,
  597,
  598,
  599,
  600,
  601,
  602,
  603,
  604,
  605,
  606,
  607,
  608,
  609,
  610,
  611,
  612,
  613,
  614,
  615,
  616,
  617,
  618,
  619,
  620,
  621,
  622,
  623,
  624,
  625,
  626,
  627,
  628,
  630,
  631,
  632,
  633,
  634,
  635,
  636,
  637,
  638,
  639,
  640,
  641,
  642,
  643,
  644,
  645,
  646,
  647,
  648,
  649,
  650,
  651,
  652,
  653,
  654,
  655,
  656,
  657,
  658,
  659,
  660,
  661,
  662,
  663,
  664,
  665,
  666,
  667,
  668,
  669,
  670,
  671,
  672,
  673,
  674,
  675,
  676,
  677,
  678,
  679,
  680,
  681,
  682,
  683,
  684,
  685,
  686,
  687,
  688,
  689,
  690,
  691,
  692,
  693,
  694,
  695,
  696,
  697,
  698,
  699,
  701,
  702,
  704,
  706,
  707,
  708,
  709,
  710,
  711,
  712,
  713,
  714,
  715,
  716,
  718,
  719,
  720,
  721,
  722,
  723,
  724,
  725,
  726,
  727,
  728,
  729,
  730,
  731,
  732,
  733,
  734,
  735,
  736,
  737,
  738,
  739,
  740,
  741,
  742,
  743,
  744,
  745,
  746,
  747,
  748,
  749,
  750,
  751,
  752,
  753,
  754,
  755,
  756,
  757,
  758,
  759,
  760,
  761,
  762,
  763,
  764,
  765,
  766,
  767,
  768,
  769,
  770,
  771,
  772,
  773,
  774,
  775,
  776,
  777,
  778,
  779,
  780,
  781,
  783,
  784,
  785,
  786,
  787,
  788,
  789,
  790,
  791,
  792,
  793,
  794,
  795,
  797,
  798,
  799,
  800,
  801,
  802,
  803,
  804,
  805,
  806,
  807,
  808,
  809,
  810,
  811,
  812,
  813,
  814,
  817,
  819,
  820,
  821,
  822,
  823,
  824,
  825,
  826,
  827,
  828,
  829,
  830,
  831,
  832,
  833,
  834,
  836,
  838,
  839,
  840,
  841,
  842,
  843,
  844,
  845,
  846,
  847,
  848,
  849,
  850,
  851,
  852,
  853,
  854,
  855,
  856,
  857,
  858,
  859,
  860,
  861,
  862,
  863,
  864,
  865,
  866,
  867,
  868,
  869,
  870,
  871,
  872,
  873,
  874,
  875,
  876,
  877,
  878,
  881,
  882,
  883,
  884,
  885,
  886,
  887,
  888,
  889,
  890,
  891,
  892,
  893,
  894,
  895,
  896,
  897,
  898,
  899,
  900,
  901,
  902,
  903,
  904,
  905,
  906,
  907,
  908,
  909,
  910,
  911,
  912,
  914,
  915,
  916,
  917,
  918,
  919,
  920,
  921,
  922,
  923,
  924,
  925,
  926,
  927,
  928,
  929,
  930,
  931,
  932,
  933,
  934,
  935,
  936,
  937,
  938,
  939,
  940,
  941,
  942,
  943,
  944,
  945,
  946,
  947,
  948,
  949,
  950,
  951,
  952,
  953,
  2797,
  2798,
  2799,
  2800,
  2801,
  2802,
  2803,
  2804,
  2805,
  2806,
  2807,
  2808,
  2809,
  2810,
  2811,
  2812,
  2813,
  2814,
  2815,
  2816,
  2817,
  2818,
  2819,
  2820,
  2821,
  2822,
  2823,
  2824,
  2825,
  2826,
  2827,
  2828,
  2829,
  2830,
  2831,
  2832,
  2833,
  2834,
  2835,
  2836,
  2837,
  2838,
  2839,
  2840,
  2841,
  2842,
  2843,
  2844,
  2845,
  2846,
  2847,
  2848,
  2849,
  2850,
  2851,
  2852,
  2853,
  2854,
  2855,
  2856,
  2857,
  2858,
  2859,
  2860,
  2861,
  2862,
  2863,
  ...]}

In [3]:
## Take a closer look at a random object
response = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/objects/1379')
json_data = response.json()
json_formatted_str = json.dumps(json_data, indent=2)
print(json_formatted_str)

{
  "objectID": 1379,
  "isHighlight": false,
  "accessionNumber": "30.120.153",
  "accessionYear": "1930",
  "isPublicDomain": true,
  "primaryImage": "https://images.metmuseum.org/CRDImages/ad/original/80920-3.jpg",
  "primaryImageSmall": "https://images.metmuseum.org/CRDImages/ad/web-large/80920-3.jpg",
  "additionalImages": [],
  "constituents": null,
  "department": "The American Wing",
  "objectName": "Candlestick",
  "title": "Candlestick",
  "culture": "",
  "period": "",
  "dynasty": "",
  "reign": "",
  "portfolio": "",
  "artistRole": "",
  "artistPrefix": "",
  "artistDisplayName": "",
  "artistDisplayBio": "",
  "artistSuffix": "",
  "artistAlphaSort": "",
  "artistNationality": "",
  "artistBeginDate": "",
  "artistEndDate": "",
  "artistGender": "",
  "artistWikidata_URL": "",
  "artistULAN_URL": "",
  "objectDate": "1790\u20131820",
  "objectBeginDate": 1790,
  "objectEndDate": 1820,
  "medium": "Brass",
  "dimensions": "7 1/4 x 5 1/4 in. (18.4 x 13.3 cm)",
  "measurements": [
    {
      "elementName": "Overall",
      "elementDescription": null,
      "elementMeasurements": {
        "Depth": 13.335,
        "Height": 18.4
      }
    }
  ],
  "creditLine": "The Sylmaris Collection, Gift of George Coe Graves, 1930",
  "geographyType": "",
  "city": "",
  "state": "",
  "county": "",
  "country": "",
  "region": "",
  "subregion": "",
  "locale": "",
  "locus": "",
  "excavation": "",
  "river": "",
  "classification": "",
  "rightsAndReproduction": "",
  "linkResource": "",
  "metadataDate": "2021-06-22T04:40:18.937Z",
  "repository": "Metropolitan Museum of Art, New York, NY",
  "objectURL": "https://www.metmuseum.org/art/collection/search/1379",
  "tags": null,
  "objectWikidata_URL": "",
  "isTimelineWork": false,
  "GalleryNumber": ""
}

In [4]:
##pulls out the ObjectID, Department, Classification and Medium of a single random object
root = 'https://collectionapi.metmuseum.org/public/collection/v1/objects/'
id = '1379'
response = requests.get(root+id)
json_data = response.json()
json_data

{'objectID': 1379,
 'isHighlight': False,
 'accessionNumber': '30.120.153',
 'accessionYear': '1930',
 'isPublicDomain': True,
 'primaryImage': 'https://images.metmuseum.org/CRDImages/ad/original/80920-3.jpg',
 'primaryImageSmall': 'https://images.metmuseum.org/CRDImages/ad/web-large/80920-3.jpg',
 'additionalImages': [],
 'constituents': None,
 'department': 'The American Wing',
 'objectName': 'Candlestick',
 'title': 'Candlestick',
 'culture': '',
 'period': '',
 'dynasty': '',
 'reign': '',
 'portfolio': '',
 'artistRole': '',
 'artistPrefix': '',
 'artistDisplayName': '',
 'artistDisplayBio': '',
 'artistSuffix': '',
 'artistAlphaSort': '',
 'artistNationality': '',
 'artistBeginDate': '',
 'artistEndDate': '',
 'artistGender': '',
 'artistWikidata_URL': '',
 'artistULAN_URL': '',
 'objectDate': '1790–1820',
 'objectBeginDate': 1790,
 'objectEndDate': 1820,
 'medium': 'Brass',
 'dimensions': '7 1/4 x 5 1/4 in. (18.4 x 13.3 cm)',
 'measurements': [{'elementName': 'Overall',
   'elementDescription': None,
   'elementMeasurements': {'Depth': 13.335, 'Height': 18.4}}],
 'creditLine': 'The Sylmaris Collection, Gift of George Coe Graves, 1930',
 'geographyType': '',
 'city': '',
 'state': '',
 'county': '',
 'country': '',
 'region': '',
 'subregion': '',
 'locale': '',
 'locus': '',
 'excavation': '',
 'river': '',
 'classification': '',
 'rightsAndReproduction': '',
 'linkResource': '',
 'metadataDate': '2021-06-22T04:40:18.937Z',
 'repository': 'Metropolitan Museum of Art, New York, NY',
 'objectURL': 'https://www.metmuseum.org/art/collection/search/1379',
 'tags': None,
 'objectWikidata_URL': '',
 'isTimelineWork': False,
 'GalleryNumber': ''}

In [5]:
## Review the different museum departments
response = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/departments')
json_data = response.json()
json_formatted_str = json.dumps(json_data, indent=2)
print(json_formatted_str)

{
  "departments": [
    {
      "departmentId": 1,
      "displayName": "American Decorative Arts"
    },
    {
      "departmentId": 3,
      "displayName": "Ancient Near Eastern Art"
    },
    {
      "departmentId": 4,
      "displayName": "Arms and Armor"
    },
    {
      "departmentId": 5,
      "displayName": "Arts of Africa, Oceania, and the Americas"
    },
    {
      "departmentId": 6,
      "displayName": "Asian Art"
    },
    {
      "departmentId": 7,
      "displayName": "The Cloisters"
    },
    {
      "departmentId": 8,
      "displayName": "The Costume Institute"
    },
    {
      "departmentId": 9,
      "displayName": "Drawings and Prints"
    },
    {
      "departmentId": 10,
      "displayName": "Egyptian Art"
    },
    {
      "departmentId": 11,
      "displayName": "European Paintings"
    },
    {
      "departmentId": 12,
      "displayName": "European Sculpture and Decorative Arts"
    },
    {
      "departmentId": 13,
      "displayName": "Greek and Roman Art"
    },
    {
      "departmentId": 14,
      "displayName": "Islamic Art"
    },
    {
      "departmentId": 15,
      "displayName": "The Robert Lehman Collection"
    },
    {
      "departmentId": 16,
      "displayName": "The Libraries"
    },
    {
      "departmentId": 17,
      "displayName": "Medieval Art"
    },
    {
      "departmentId": 18,
      "displayName": "Musical Instruments"
    },
    {
      "departmentId": 19,
      "displayName": "Photographs"
    },
    {
      "departmentId": 21,
      "displayName": "Modern Art"
    }
  ]
}

In [2]:
##Creates an empty Dataframe
columns = ['ObjectID', 'Department','Classification','Medium','Object_Name','Title','Date','BeginDate','EndDate']
df = pd.DataFrame(columns=columns)

In [4]:
##Creates a list of Object IDs from a single Department
response = requests.get("https://collectionapi.metmuseum.org/public/collection/v1/objects?departmentIds=9")
json_data = response.json()
id_list = json_data['objectIDs']
print(len(id_list))

174988

#### Begin Downloading object data. This step is broken down into segments that were completed over the course of several days.

In [5]:
## Segments the object list into a shorter list using a range from id_list
short_list = id_list[0:70000]
print(len(short_list))

70000

In [6]:
##Iterates through the short_list and adds the ObjectID, Department, Classification, and Medium to a dataframe
start_time = time.time()
root = 'https://collectionapi.metmuseum.org/public/collection/v1/objects/'
for y in short_list:
    id = str(y)
    response = requests.get(root+id)
    json_data = response.json()
    class_value = json_data['classification']
    objectid = json_data['objectID']
    department = json_data['department']
    medium = json_data['medium']
    object_name = json_data['objectName']
    title = json_data['title']
    date = json_data['objectDate']
    begin_date = json_data['objectBeginDate']
    end_date = json_data['objectEndDate']
    new_row = pd.DataFrame({'ObjectID': [objectid], 'Department': [department], 'Classification': [class_value], 'Medium': [medium], 'Object_Name':[object_name], 'Title':[title], 'Date': [date], 'BeginDate': [begin_date], 'EndDate': [end_date]})
    df = pd.concat([df, new_row], ignore_index=True)
end_time = time.time()
elapsed_time = end_time - start_time
print(elapsed_time)

18752.85183262825

#### At this point, return to the above step and run another segment.
#### When all the objects from this department have been downloaded, start with another department.

In [9]:
df

,ObjectID,Department,Classification,Medium,Object_Name,Title,Date,BeginDate,EndDate
0,333951,Drawings and Prints,Books,Illustrations: etching and engraving,Book ; ornament and architecture,"Chinese Architecture, Civil and Ornamental [bo...",1759,1759,1759
1,333952,Drawings and Prints,Books,Illustrations: etching and engraving,Book ; ornament and architecture,Gothic Architecture Decorated [bound with: Got...,1759,1759,1759
2,333953,Drawings and Prints,Prints,Etching and drypoint,Print,"Isabel de Bourbon on horseback, after Velázquez",1778,1778,1778
3,333954,Drawings and Prints,Prints,Etching,Print,"Philip IV on horseback, after Velázquez",1778,1778,1778
4,333955,Drawings and Prints,Prints,Etching,Print,"Portrait of the court dwarf known as el Primo,...",1778,1778,1778
...,...,...,...,...,...,...,...,...,...
69995,407281,Drawings and Prints,Prints,Commercial color lithograph,Print,"Japan, from Flags of All Nations, Series 1 (N9...",1887,1887,1887
69996,407282,Drawings and Prints,Prints,Commercial color lithograph,Print,"Korea, from Flags of All Nations, Series 1 (N9...",1887,1887,1887
69997,407283,Drawings and Prints,Prints,Commercial color lithograph,Print,"Hawaiian Islands, from Flags of All Nations, S...",1887,1887,1887
69998,407284,Drawings and Prints,Prints,Commercial color lithograph,Print,"Virginia and France (double-printed card), fro...",1887,1887,1887
69999,407285,Drawings and Prints,Prints,Commercial color lithograph,Print,"Egypt, from Flags of All Nations, Series 1 (N9...",1887,1887,1887

In [18]:
## Take a look at one classification
cell_value = df.loc[3, 'Classification']
print(cell_value)

Main dress-Childrenswear-Boy's

In [19]:
unique_classifications = df['Classification'].unique()
unique_class_list = sorted(unique_classifications)
unique_class_list

['(not assigned)',
 'Accessory',
 'Accessory-Foot and Leg wear',
 'Accessory-Foot and Leg wear-Childrenswear',
 'Accessory-Foot and Leg wear-Menswear',
 'Accessory-Foot and Leg wear-Unisex',
 'Accessory-Foot and Leg wear-Womenswear',
 'Accessory-Headwear',
 'Accessory-Headwear-Menswear',
 'Accessory-Headwear-Womenswear',
 'Accessory-Jewelry',
 'Accessory-Jewelry-Womenswear',
 'Accessory-Neckwear',
 'Accessory-Neckwear-Womenswear',
 'Accessory-Waist',
 'Accessory-Waist-Menswear',
 'Architectural Models',
 'Archives',
 'Arms and Armor',
 'Basketry',
 'Ceramics',
 'Ceramics-Faience',
 'Ceramics-Porcelain',
 'Ceramics-Porcelain-Export',
 'Ceramics-Pottery',
 'Ceramics-Tiles',
 'Chess Sets',
 'Chess Sets-Reproductions',
 'Codices',
 'Coins',
 'Drawings',
 'Enamels',
 'Enamels-Painted',
 'Fans',
 'Furniture',
 'Furniture-Wood',
 'Gaming pieces',
 'Glass',
 'Glass-Enameled',
 'Glass-Painted',
 'Glass-Stained',
 'Horology',
 'Ivories and Bone',
 'Jewelry',
 'Lacquer',
 'Lapidary Work',
 'Leather',
 'Lighting',
 'Main dress',
 'Main dress-Childrenswear',
 "Main dress-Childrenswear-Boy's",
 "Main dress-Childrenswear-Girl's",
 'Main dress-Menswear',
 'Main dress-Womenswear',
 'Medals and Plaquettes',
 'Medals and Plaquettes-Reproductions',
 'Metal',
 'Metalwork',
 'Metalwork-Aluminum',
 'Metalwork-Base Metal',
 'Metalwork-Brass',
 'Metalwork-Bronze',
 'Metalwork-Chromium',
 'Metalwork-Copper',
 'Metalwork-Electrotype',
 'Metalwork-Enamel',
 'Metalwork-Gilt Bronze',
 'Metalwork-Gold',
 'Metalwork-Gold and Platinum',
 'Metalwork-Iron',
 'Metalwork-Latten',
 'Metalwork-Mixed Metals',
 'Metalwork-Pewter',
 'Metalwork-Silver',
 'Metalwork-Silver In Combination',
 'Metalwork-Silverplate',
 'Metalwork-Steel',
 'Miscellaneous',
 'Miscellaneous-Wood',
 'Miscellany',
 'Natural Substances',
 'Natural Substances-Ivory',
 'Natural Substances-Leatherwork',
 'Natural Substances-Rock Crystal',
 'Night and Dressing Wear',
 'Outerwear',
 'Outerwear-Menswear',
 'Outerwear-Womenswear',
 'Paintings',
 'Paintings-Decorative',
 'Papier Mâché',
 'Photographs',
 'Plastic',
 'Prints',
 'Reproductions',
 'Reproductions-Models',
 'Sculpture',
 'Sculpture-Architectural',
 'Sculpture-Bronze',
 'Sculpture-Miniature',
 'Sculpture-Reproductions',
 'Sculpture-Reproductions-Casts',
 'Seals',
 'Stone',
 'Textiles',
 'Textiles-Brocades',
 'Textiles-Costumes',
 'Textiles-Dyed',
 'Textiles-Ecclesiastical',
 'Textiles-Embroidered',
 'Textiles-Laces',
 'Textiles-Miscellaneous',
 'Textiles-Painted',
 'Textiles-Painted and Dyed',
 'Textiles-Painted and Printed',
 'Textiles-Painted and/or Printed',
 'Textiles-Printed',
 'Textiles-Rugs',
 'Textiles-Sample Books',
 'Textiles-Tapestries',
 'Textiles-Trimmings',
 'Textiles-Velvets',
 'Textiles-Woven',
 'Vases',
 'Wood',
 'Woodwork',
 'Woodwork-Architectural',
 'Woodwork-Furniture',
 'Woodwork-Lacquer',
 'Works on Paper']

In [8]:
df.to_csv('Department_9.csv', index=False)

Downloading Object Numbers separately because I forgot them last time. 
I'll join the Object Numbers to the rest of the data in sql.

In [11]:
##Creates an empty Dataframe
columns = ['ObjectID', 'ObjectNumber']
df = pd.DataFrame(columns=columns)

In [12]:
response = requests.get("https://collectionapi.metmuseum.org/public/collection/v1/objects?")
json_data = response.json()
id_list = json_data['objectIDs']
print(len(id_list))

488697

In [16]:
##Creates a shorter list using a range from id_list
short_list = id_list[307035:488662]
print(len(short_list))

181627

In [17]:
start_time = time.time()
root = 'https://collectionapi.metmuseum.org/public/collection/v1/objects/'
for y in short_list:
    id = str(y)
    response = requests.get(root+id)
    json_data = response.json()
    objectid = json_data['objectID']
    objectnumber = json_data['accessionNumber']
    new_row = pd.DataFrame({'ObjectID': [objectid], 'ObjectNumber': [objectnumber], })
    df = pd.concat([df, new_row], ignore_index=True)
end_time = time.time()
elapsed_time = end_time - start_time
print(elapsed_time)

48668.22785401344

In [18]:
df

       ObjectID ObjectNumber
0        396969   37.35.2(6)
1        396970   37.35.2(4)
2        396971   37.35.2(3)
3        396972   37.35.2(5)
4        396973   37.35.2(2)
...         ...          ...
225613   913001   33.30(339)
225614   913002   33.30(341)
225615   913003   33.30(342)
225616   913004   33.30(343)
225617   913005    24.66.867

[225618 rows x 2 columns]

In [19]:
df.to_csv('ObjectNumbers2.csv', index=False)

In [ ]:
263044